# frozen_string_literal: true

source "https://rubygems.org"

gem "atproto_auth", path: "../.."
gem "dotenv"
gem "faraday"
gem "json"
gem "puma"
gem "rackup"
gem "redis"
gem "sinatra"
gem "sinatra-contrib"
gem "sqlite3", "~> 2.9"
